---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jal7434-test-flask
  labels:
    app: jal7434-test-flask
spec:
  replicas: 2
  selector:
   matchLabels:
     app: jal7434-test-flask
  template:
    metadata:
      labels:
        app: jal7434-test-flask

    spec:
      containers:
       - name: jal7434-test-flask
         imagePullPolicy: Always
         image: jal7434/hw05:0.2
         command: ['python3','app.py']
         ports:
         - name: http
           containerPort: 5000
