---
apiVersion: v1
kind: Service
metadata:
  name: jal7434-redis-service 
spec:
  type: ClusterIP
  selector:
    app: jal7434-test-redis
  ports:
  - name: jal7434-test-redis
    port: 6379
    targetPort: 6379
