---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jal7434-data
  labels:
    app: jal7434-test-redis
    username: jal7434
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
